version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - bluestore-db:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    env_file: .env
    environment:
      - REDIS_PASSWORD:${REDIS_PASSWORD}
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - bluestore-redis:/var/lib/redis/key
  
  nginx:
    depends_on:
      - bluestore
    restart: always
    build:
      context: ./nginx
    ports:
      # - "3050:80"
      - "80:80"
      - "443:443"

  bluestore:
    build:
      context: .
    env_file: .env
    environment:
      - REDIS_HOST:${REDIS_HOST}
      - DB_HOST:${DB_HOST}
      - DB_SCHEMA:${DB_SCHEMA}
      - DB_USER:${DB_USER}
      - DB_PASSWORD:${DB_USER}
      - REDIS_USER:${DB_USER}
      - REDIS_PASSWORD:${REDIS_PASSWORD}
      - REDIS_PORT:${REDIS_PORT}
      - COINBASE_API_KEY:${COINBASE_API_KEY}
    depends_on:
      - postgres
      - redis

volumes:
  bluestore-db:
  bluestore-redis:
