version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    #restart: always
    volumes:
      - bluestore-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    env_file: .env
    environment:
      - REDIS_PASSWORD:${REDIS_PASSWORD}
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - bluestore-redis:/var/lib/redis/key
    ports:
      - "6379:6379"
     
  nginx:
    depends_on:
      - bluestore_1
      - bluestore_2
      - bluestore_3
      - bluestore_4
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"

  bluestore_1:
    build:
      context: .
    env_file: .env
    environment:
      - REDIS_HOST:${REDIS_HOST}
      - DB_HOST:${DB_HOST}
      - DB_SCHEMA:${DB_SCHEMA}
      - DB_USER:${DB_USER}
      - DB_PASSWORD:${DB_USER}
      - REDIS_USER:${DB_USER}
      - REDIS_PASSWORD:${REDIS_PASSWORD}
      - REDIS_PORT:${REDIS_PORT}
      - COINBASE_API_KEY:${COINBASE_API_KEY}
      - SHAREDSECRET:${SHAREDSECRET}
      - PORT=${PORT_1}
      - BINANCE_MARCHANTID=${BINANCE_MARCHANTID}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}
    depends_on:
      - postgres
      - redis
    volumes:
       - bluestore-storeage:/app/resources
  
  bluestore_2:
    build:
      context: .
    env_file: .env
    environment:
      - REDIS_HOST:${REDIS_HOST}
      - DB_HOST:${DB_HOST}
      - DB_SCHEMA:${DB_SCHEMA}
      - DB_USER:${DB_USER}
      - DB_PASSWORD:${DB_USER}
      - REDIS_USER:${DB_USER}
      - REDIS_PASSWORD:${REDIS_PASSWORD}
      - REDIS_PORT:${REDIS_PORT}
      - COINBASE_API_KEY:${COINBASE_API_KEY}
      - SHAREDSECRET:${SHAREDSECRET}
      - PORT=${PORT_2}
      - BINANCE_MARCHANTID=${BINANCE_MARCHANTID}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}
    depends_on:
      - postgres
      - redis
    volumes:
       - bluestore-storeage:/app/resources

  bluestore_3:
    build:
      context: .
    env_file: .env
    environment:
      - REDIS_HOST:${REDIS_HOST}
      - DB_HOST:${DB_HOST}
      - DB_SCHEMA:${DB_SCHEMA}
      - DB_USER:${DB_USER}
      - DB_PASSWORD:${DB_USER}
      - REDIS_USER:${DB_USER}
      - REDIS_PASSWORD:${REDIS_PASSWORD}
      - REDIS_PORT:${REDIS_PORT}
      - COINBASE_API_KEY:${COINBASE_API_KEY}
      - SHAREDSECRET:${SHAREDSECRET}
      - PORT:${PORT_3}
      - BINANCE_MARCHANTID=${BINANCE_MARCHANTID}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}
    depends_on:
      - postgres
      - redis
    volumes:
       - bluestore-storeage:/app/resources
  
  bluestore_4:
    build:
      context: .
    env_file: .env
    environment:
      - REDIS_HOST:${REDIS_HOST}
      - DB_HOST:${DB_HOST}
      - DB_SCHEMA:${DB_SCHEMA}
      - DB_USER:${DB_USER}
      - DB_PASSWORD:${DB_USER}
      - REDIS_USER:${DB_USER}
      - REDIS_PASSWORD:${REDIS_PASSWORD}
      - REDIS_PORT:${REDIS_PORT}
      - COINBASE_API_KEY:${COINBASE_API_KEY}
      - SHAREDSECRET:${SHAREDSECRET}
      - PORT=${PORT_4}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}
    depends_on:
      - postgres
      - redis
    volumes:
       - bluestore-storeage:/app/resources
volumes:
  bluestore-db:
  bluestore-redis:
  bluestore-storeage:

