version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # ports:
    #   - "5432:5432"
    volumes:
      - bluestore-db:/var/lib/postgresql/data
    # networks:
    #     - example-net

  redis:
    image: redis:alpine
    # command: ["redis-server", "--bind", "redis", "--port", "6379"]
    # ports:
    #   - "6379:6379"
    volumes:
      - bluestore-redis:/var/lib/redis/key
    # networks:
    #     - example-net
  
  nginx:
    depends_on:
      - bluestore
    restart: always
    build:
      context: ./nginx
    ports:
      - "3050:80"
    # networks:
    #     - example-net

  bluestore:
    build:
      context: .
    # container_name: bluestore
    # hostname: bluestore
    environment:
      # PORT: 3000
      REDIS_HOST: redis
      DB_HOST: postgres
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_USER: default
      REDIS_PASSWORD: 123456
      REDIS_PORT: 6379
      COINBASE_API_KEY: 0b427908-e03a-414b-a569-fa14db4cc601
    depends_on:
      - postgres
      - redis
    # ports:
    #   - "3000:3000"
    # networks:
    #     - example-net  

volumes:
  bluestore-db:
  bluestore-redis:

# networks:
#   example-net:
#     external: true
